version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:                   
      - .env                    
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_TYPEORM_SYNCHRONIZE=${POSTGRES_TYPEORM_SYNCHRONIZE}
      - POSTGRES_TYPEORM_DROP_SCHEMA=${POSTGRES_TYPEORM_DROP_SCHEMA}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - THROTTLE_TTL=${THROTTLE_TTL}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT}
    ports:
      - '9000:${PORT}'
    depends_on:
      - postgres-salt-test
    restart: unless-stopped

  postgres-salt-test:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - '5432:5432'
    restart: unless-stopped
